dashboard_import:
  package_import_url: github://MariuszWoszczynski/Level-sensor-sr04/level-sensor-short-distance.yaml@main
  import_full_config: true
 
substitutions:
  name: level-sensor-short-distance
  friendly_name: Level sensor (short distance)
  
esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  project:
    name: esphome.level_sensor_short_distance
    version: "1.0"
 
esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Status LED for connection
status_led:
  pin:
    # Blue LED
    number: GPIO02

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "QW7XkQg+3xMNyro/oVNWf35bOuaySxFrmSzinzNU6sc="

ota:
  - platform: esphome
    password: "7aecec103a1f39b3aa2251c1827129da"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  output_power: 18dB
#  static IP configuration (instead of data from the secret file)
#  manual_ip:
#    static_ip: 192.168.1.100
#    gateway: 192.168.1.1
#    subnet: 255.255.255.0
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Level-Sensor"

captive_portal:
    
web_server:
  port: 80
  version: 3

button:
  # Restart the ESP
  - platform: restart
    name: "Restart"

text_sensor: 
    #diagnostic info
  - platform: wifi_info                   
    ip_address:
      name: 'IP Address'
      icon: mdi:wifi
    ssid:
      name: 'Connected SSID'
      icon: mdi:wifi-strength-2

sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"

  - platform: ultrasonic
    trigger_pin: GPIO33
    echo_pin: GPIO25
    name: "Distance [m]"
    id: water_distance
    pulse_time: 150us
    update_interval: 1s
    filters:
      - filter_out: 6.0
      - filter_out: 0.0
      - median:
          window_size: 5
          send_every: 1
  

  - platform: template
    name: "Water Level [%]"
    unit_of_measurement: "%"
    accuracy_decimals: 1
    lambda: |-
      const float max_distance = 0.7;   // Odległość przy pustym zbiorniku (m)
      const float min_distance = 0.3;   // Odległość przy pełnym zbiorniku (m)
      float distance = id(water_distance).state;
      float percent = ((max_distance - distance) / (max_distance - min_distance)) * 100.0;
      if (percent > 100.0) return 100.0;
      if (percent < 0.0) return 0.0;
      return percent;
    update_interval: 2s
